### ISSUE TITLE
Permissions being checked before assigned by LuckPerms.

### ISSUE THREAD

**Issue by mibby** [Esophose/PlayerParticles#70]
RE: https://github.com/Esophose/PlayerParticles/commit/668191202d398068ee4b00d403cf1540598b2384#commitcomment-46878982

PlayerParticles dev 51
https://ci.codemc.io/job/Esophose/job/PlayerParticles/

``check-permissions-on-login: true`` is not a safe setting for fixed particles used for server block locations (portals, spawn point, etc). It might be checking permissions before LuckPerms sets them on login, causing fixed particles used to wipe despite having full permissions.

Also;
> forgot to negate the style permission check

**Comment by Esophose** [comment]
I believe LuckPerms loads permissions during the time that the player establishes connection to the server and will prevent them from joining until it loads their permissions, so that shouldn't be part of the problem. This should be resolved in [dev 52](https://ci.codemc.io/job/Esophose/job/PlayerParticles/52/).

**Comment by mibby** [comment]
Seems to be working and fixed now, thanks. Relogging no longer deletes the fixed particles. I still believe there should be a way to set fixed particles that have an owner type of ``server`` so there is no way for them to be removed and it avoids the permission checks for performance reasons.
